In [1]:
import pandas as pd
import Levenshtein
from Bio import SeqIO

In [2]:
#Read the query and sequences from the .fasta file
fasta_file = "123_CAMI.fasta"  

# Create empty lists to store the data
queries = []
sequences = []

# Read through the FASTA file and extract query and sequence information
for record in SeqIO.parse(fasta_file, "fasta"):
    queries.append(record.id)
    sequences.append(str(record.seq))

# Create DataFrame from the lists
fasta_df = pd.DataFrame({'Query': queries, 'Sequence': sequences})

# Display the DataFrame
print(fasta_df)

                                                 Query
0          gb|DQ241380.1|+|0-777|ARO:3002539|AAC(3)-IV  \
1    gb|AE006468.2|+|1707351-1707789|ARO:3002571|AA...
2      gb|AB462903|+|1199-1751|ARO:3002574|AAC(6')-Iaf
3    gb|FJ503047|+|0-519|ARO:3002592|AAC(6')-Ib-Han...
4    gb|EU085533|+|0-519|ARO:3002591|AAC(6')-Ib-Suzhou
..                                                 ...
693  gb|KU736867.1|+|19653-21573|ARO:3004442|tet(W/...
694     gb|AL009126.3|-|339155-339749|ARO:3003059|tmrB
695        gb|U00096|-|2098446-2099613|ARO:3003577|ugd
696            gb|M90056.1|+|908-2477|ARO:3002829|vgaA
697            gb|DQ823382|+|0-1569|ARO:3002830|vgaALC

                                              Sequence
0    GTGCAATACGAATGGCGAAAAGCCGAGCTCATCGGTCAGCTTCTCA...
1    ATGGACATCAGGCAAATGAACAGAACCCATCTGGATCACTGGCGCG...
2    TTGGACTATTCAATATGCGATATAGCTGAATCAAATGAATTAATCC...
3    ATGACTGAGCATGACCTTGTGATGCTCTATGAGTGGCTAAATCGAT...
4    ATGACTGAGCATGACCTTGCGATGCTCTATGAGTGGCTAAATCGAT...
..                                                 ...
693  ATGAAAATAATCAATATTGGAATTCTTGCCCATGTAGACGCTGGAA...
694  ATGATCATTTGGATAAACGGGGCATTCGGTTCGGGAAAAACACAAA...
695  ATGAAAATCACCATTTCCGGTACTGGCTATGTAGGCTTGTCAAACG...
696  ATGAAAATAATGTTAGAGGGACTTAATATAAAACATTATGTTCAAG...
697  ATGAAAATACTGTTAGAGGGACTTCATATAAAACATTATGTTCAAG...

[698 rows x 2 columns]

In [3]:
fasta_df=fasta_df.sort_values("Query")
fasta_df=fasta_df.reset_index(drop=True)
fasta_df

,Query,Sequence
0,gb|AB023477|+|0-861|ARO:3001082|SHV-24,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...
1,gb|AB049569|+|0-861|ARO:3000958|TEM-91,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...
2,gb|AB200915.1|-|1831-2305|ARO:3005084|dfrA31,ATGAAAATATCCATTATGGCAGCAGTTTCTGAGAATGGAGTAATTG...
3,gb|AB302939|+|8-869|ARO:3001115|SHV-60,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...
4,gb|AB372881|+|8-869|ARO:3001160|SHV-111,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...
...,...,...
693,gb|Y17582|+|0-858|ARO:3000892|TEM-21,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...
694,gb|Y17583|+|213-1071|ARO:3000893|TEM-22,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...
695,gb|Y17584|+|0-858|ARO:3000899|TEM-29,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...
696,gb|Z22590|+|154-955|ARO:3001406|OXA-11,ATGAAAACATTTGCCGCATATGTAATTATCGCGTGTCTTTCGAGTA...
697,gb|Z54241.1|+|529-1051|ARO:3002559|AAC(6')-Ip,ATGCTTAAGAAAAGCTTTCTTGATGCTGGAAATGAATCATGGGGAG...

In [4]:
fasta_df.to_csv("testSequences.tsv",sep="\t")

In [5]:
# Create a dataframe for Bandage Combined1
master_df= pd.read_csv('QueriesAndResultsMasterList.tsv', sep='\t')

In [6]:
master_df.columns

Index(['Unnamed: 0', 'Query', 'Sequence_x', 'Length_Bandage', 'Path_Bandage',
       'Start_Bandage', 'End_Bandage', 'Sequence_Bandage', 'Sequence_y',
       'Length_x', 'Start_SPAligner', 'End_SPAligner', 'Length_SPAligner',
       'Path_SPAligner', 'Sequence_SPAligner', 'Sequence', 'Length_y',
       'Path_GraphAligner', 'Start_GraphAligner', 'End_GraphAligner',
       'BandageVSSPAligner', 'BandageVSGraphAligner',
       'SPAlignerVSGraphAligner'],
      dtype='object')

In [7]:
sequences_df=master_df[['Sequence_Bandage','Sequence_SPAligner']]
sequences_df

,Sequence_Bandage,Sequence_SPAligner
0,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,999
1,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...
2,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...
3,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...
4,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...
...,...,...
373,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...
374,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...
375,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...
376,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...
377,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...

In [8]:
merged_df = pd.merge(fasta_df, sequences_df,left_index=True, right_index=True)

In [9]:
merged_df.dtypes

Query                 object
Sequence              object
Sequence_Bandage      object
Sequence_SPAligner    object
dtype: object

In [10]:
merged_df['Sequence_Bandage']=merged_df['Sequence_Bandage'].astype(str)

In [11]:
#Create a method to calculate the levenstein distance
def calculate_edit_distance_query_bandage(row):
    return Levenshtein.distance(row['Sequence'], row['Sequence_Bandage'])

In [12]:
merged_df['edit_distance_query_bandage'] = merged_df.apply(calculate_edit_distance_query_bandage, axis=1)

In [13]:
merged_df

,Query,Sequence,Sequence_Bandage,Sequence_SPAligner,edit_distance_query_bandage
0,gb|AB023477|+|0-861|ARO:3001082|SHV-24,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,999,7
1,gb|AB049569|+|0-861|ARO:3000958|TEM-91,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,4
2,gb|AB200915.1|-|1831-2305|ARO:3005084|dfrA31,ATGAAAATATCCATTATGGCAGCAGTTTCTGAGAATGGAGTAATTG...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,500
3,gb|AB302939|+|8-869|ARO:3001115|SHV-60,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,5
4,gb|AB372881|+|8-869|ARO:3001160|SHV-111,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,8
...,...,...,...,...,...
373,gb|GQ390809|+|0-813|ARO:3001174|SHV-127,ATGCGTTTTATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,323
374,gb|GQ423625.1|+|0-825|ARO:3001442|OXA-117,ATGAACATTAAAGCACTCTTACTTATAACAAGCGCTATTTTTATTT...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,440
375,gb|GQ853679|+|0-825|ARO:3001453|OXA-148,ATGAACATTAAAGCACTCTTACTTATAACAAGCGCTATTTTTATTT...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,439
376,gb|GQ853680|+|0-825|ARO:3001454|OXA-149,ATGAACATTAAAGCCCTCTTACTTATAACAAGCGCTATTTTTATTT...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,439
377,gb|GQ853681|+|0-825|ARO:3001455|OXA-150,ATGAACATTAAAGCACTCTTACTTATAACAAGCGCTATTTTTATTT...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,439

In [14]:
#Create a method to calculate the levenstein distance
def calculate_edit_distance_query_spaligner(row):
    return Levenshtein.distance(row['Sequence'], row['Sequence_SPAligner'])

In [15]:
merged_df['edit_distance_query_spaligner'] = merged_df.apply(calculate_edit_distance_query_spaligner, axis=1)

In [16]:
merged_df

,Query,Sequence,Sequence_Bandage,Sequence_SPAligner,edit_distance_query_bandage,edit_distance_query_spaligner
0,gb|AB023477|+|0-861|ARO:3001082|SHV-24,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,999,7,861
1,gb|AB049569|+|0-861|ARO:3000958|TEM-91,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,4,4
2,gb|AB200915.1|-|1831-2305|ARO:3005084|dfrA31,ATGAAAATATCCATTATGGCAGCAGTTTCTGAGAATGGAGTAATTG...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,500,500
3,gb|AB302939|+|8-869|ARO:3001115|SHV-60,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,5,5
4,gb|AB372881|+|8-869|ARO:3001160|SHV-111,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,8,8
...,...,...,...,...,...,...
373,gb|GQ390809|+|0-813|ARO:3001174|SHV-127,ATGCGTTTTATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,323,323
374,gb|GQ423625.1|+|0-825|ARO:3001442|OXA-117,ATGAACATTAAAGCACTCTTACTTATAACAAGCGCTATTTTTATTT...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,440,440
375,gb|GQ853679|+|0-825|ARO:3001453|OXA-148,ATGAACATTAAAGCACTCTTACTTATAACAAGCGCTATTTTTATTT...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,439,439
376,gb|GQ853680|+|0-825|ARO:3001454|OXA-149,ATGAACATTAAAGCCCTCTTACTTATAACAAGCGCTATTTTTATTT...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,439,439
377,gb|GQ853681|+|0-825|ARO:3001455|OXA-150,ATGAACATTAAAGCACTCTTACTTATAACAAGCGCTATTTTTATTT...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,439,439

In [17]:
#Create a method to calculate the levenstein distance
def calculate_edit_distance_bandage_spaligner(row):
    return Levenshtein.distance(row['Sequence_Bandage'], row['Sequence_SPAligner'])

In [18]:
merged_df['edit_distance_query_bandage_spaligner'] = merged_df.apply(calculate_edit_distance_bandage_spaligner, axis=1)

In [19]:
merged_df

,Query,Sequence,Sequence_Bandage,Sequence_SPAligner,edit_distance_query_bandage,edit_distance_query_spaligner,edit_distance_query_bandage_spaligner
0,gb|AB023477|+|0-861|ARO:3001082|SHV-24,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,999,7,861,861
1,gb|AB049569|+|0-861|ARO:3000958|TEM-91,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,4,4,0
2,gb|AB200915.1|-|1831-2305|ARO:3005084|dfrA31,ATGAAAATATCCATTATGGCAGCAGTTTCTGAGAATGGAGTAATTG...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,500,500,0
3,gb|AB302939|+|8-869|ARO:3001115|SHV-60,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,5,5,0
4,gb|AB372881|+|8-869|ARO:3001160|SHV-111,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGCGTTATATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,8,8,0
...,...,...,...,...,...,...,...
373,gb|GQ390809|+|0-813|ARO:3001174|SHV-127,ATGCGTTTTATTCGCCTGTGTATTATCTCCCTGTTAGCCACCCTGC...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,323,323,0
374,gb|GQ423625.1|+|0-825|ARO:3001442|OXA-117,ATGAACATTAAAGCACTCTTACTTATAACAAGCGCTATTTTTATTT...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,440,440,0
375,gb|GQ853679|+|0-825|ARO:3001453|OXA-148,ATGAACATTAAAGCACTCTTACTTATAACAAGCGCTATTTTTATTT...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,439,439,0
376,gb|GQ853680|+|0-825|ARO:3001454|OXA-149,ATGAACATTAAAGCCCTCTTACTTATAACAAGCGCTATTTTTATTT...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,439,439,0
377,gb|GQ853681|+|0-825|ARO:3001455|OXA-150,ATGAACATTAAAGCACTCTTACTTATAACAAGCGCTATTTTTATTT...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGG...,439,439,0

In [20]:
merged_df.to_csv('EditDistance.tsv',sep='\t')

In [21]:
merged_df.columns

Index(['Query', 'Sequence', 'Sequence_Bandage', 'Sequence_SPAligner',
       'edit_distance_query_bandage', 'edit_distance_query_spaligner',
       'edit_distance_query_bandage_spaligner'],
      dtype='object')

In [22]:
merged_df['edit_distance_query_bandage_spaligner'].value_counts()

edit_distance_query_bandage_spaligner
0       212
861      96
858       8
791       6
780       5
785       3
789       2
420       2
859       2
853       2
856       2
794       2
831       2
16        2
1053      1
2007      1
474       1
825       1
660       1
820       1
1134      1
678       1
1167      1
857       1
732       1
642       1
381       1
753       1
9         1
2219      1
764       1
771       1
1155      1
781       1
1920      1
1644      1
1158      1
18        1
1725      1
729       1
372       1
818       1
1758      1
795       1
1299      1
843       1
Name: count, dtype: int64

In [23]:
type_counts_bandage_spaligner=merged_df['edit_distance_query_bandage_spaligner'].value_counts().reset_index()

In [24]:
# Rename the columns
type_counts_bandage_spaligner.columns = ['Type', 'Count']

# Display the result
print(type_counts_bandage_spaligner)

    Type  Count
0      0    212
1    861     96
2    858      8
3    791      6
4    780      5
5    785      3
6    789      2
7    420      2
8    859      2
9    853      2
10   856      2
11   794      2
12   831      2
13    16      2
14  1053      1
15  2007      1
16   474      1
17   825      1
18   660      1
19   820      1
20  1134      1
21   678      1
22  1167      1
23   857      1
24   732      1
25   642      1
26   381      1
27   753      1
28     9      1
29  2219      1
30   764      1
31   771      1
32  1155      1
33   781      1
34  1920      1
35  1644      1
36  1158      1
37    18      1
38  1725      1
39   729      1
40   372      1
41   818      1
42  1758      1
43   795      1
44  1299      1
45   843      1

In [25]:
type_counts_bandage_spaligner.to_csv("type_counts_bandage_spaligner.tsv",sep='\t')

In [26]:
type_counts_query_spaligner=merged_df['edit_distance_query_spaligner'].value_counts().reset_index()

In [27]:
# Rename the columns
type_counts_query_spaligner.columns = ['Type', 'Count']

# Display the result
print(type_counts_query_spaligner)

     Type  Count
0     861     69
1     825     23
2     311     13
3     437     12
4     310      9
..    ...    ...
125    35      1
126   775      1
127   441      1
128   449      1
129   323      1

[130 rows x 2 columns]

In [28]:
type_counts_query_spaligner.to_csv("type_counts_query_spaligner.tsv",sep='\t')

In [29]:
type_counts_query_bandage=merged_df['edit_distance_query_bandage'].value_counts().reset_index()

In [30]:
# Rename the columns
type_counts_query_bandage.columns = ['Type', 'Count']

# Display the result
print(type_counts_query_bandage)

     Type  Count
0     311     23
1     312     14
2     310     13
3     437     12
4       7     12
..    ...    ...
153  1090      1
154  1218      1
155   863      1
156   821      1
157   323      1

[158 rows x 2 columns]

In [31]:
type_counts_query_bandage.to_csv("type_counts_query_bandage.tsv",sep='\t')